package com.autopilot.service.deployment.module;

import lombok.Builder;
import lombok.Data;
import java.util.List;
import java.util.Map;

/**
 * Represents the observed state of a deployment post-execution.
 * Generated by runtime inspection and passed to validators.
 */
@Data
@Builder
public class RuntimeSnapshot {
    private String deploymentId;
    private List<String> runningContainers;
    private Map<String, Integer> activePorts;
    private List<String> discoveredAssetPaths;
    private List<String> startupLogsSnippet;
}
