spring.application.name=autopilot-backend
server.port=8080

# Enable Java 21 virtual threads
spring.threads.virtual.enabled=true

# -----------------------------
# DATABASE CONFIG (MySQL)
# -----------------------------

spring.datasource.url=jdbc:mysql://localhost:3306/autopilot
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# -----------------------------
# REDIS CONFIG
# -----------------------------

spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.timeout=60000
spring.data.redis.connect-timeout=60000




# -----------------------------
# TERRAFORM CONFIG
# -----------------------------

terraform.directory=src/main/resources/terraform

# -----------------------------
# LOGGING
# -----------------------------

logging.level.root=INFO
logging.level.com.autopilot=DEBUG
