spring.application.name=autopilot-backend
server.port=8080

# -----------------------------
# DATABASE CONFIG (MySQL)
# -----------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/autopilot?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# -----------------------------
# REDIS CONFIG
# -----------------------------
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.timeout=60000
spring.data.redis.connect-timeout=60000
spring.data.redis.repositories.enabled=false

# -----------------------------
# TERRAFORM CONFIG
# -----------------------------
terraform.directory=src/main/resources/terraform

# -----------------------------
# LOGGING
# -----------------------------
logging.level.root=INFO
logging.level.com.autopilot=DEBUG

# -----------------------------
# JWT CONFIG
# -----------------------------
jwt.secret=dGhpcyBpcyBhIHN1cGVyIHNlY3JldCBrZXkgZm9yIGF1dG9waWxvdCBqd3Qgc2lnbmluZyEhIQ==
jwt.expiration-ms=604800000

# -----------------------------
# GOOGLE OAUTH2
# -----------------------------
spring.security.oauth2.client.registration.google.client-id=886099436405-l6cli0n09jfc0s53mumkt3laji6v0jrn.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# -----------------------------
# LLM CONFIG (Universal Analyzer)
# -----------------------------
stellar.url=http://localhost:11434/api/generate
stellar.model=llama3.2
