package com.autopilot.service.deployment;

import com.autopilot.analyzer.RepoAnalyzerService;
import com.autopilot.analyzer.model.RepoAnalysisResult;
import com.autopilot.analyzer.model.ServiceConfig;
import com.autopilot.entity.Deployment;
import com.autopilot.enums.DeploymentStatus;
import com.autopilot.repository.DeploymentRepository;
import com.autopilot.service.aws.DockerPushService;

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class DeploymentPipelineService {

    private final RepoAnalyzerService repoAnalyzerService;
    private final DockerfileGenerator dockerfileGenerator;
    private final DockerBuilder dockerBuilder;
    private final DockerPushService dockerPushService;
    private final DeploymentRepository deploymentRepository;

    private static final String WORKSPACE_ROOT = "/tmp/autopilot-workspaces";

    public void execute(Deployment deployment) {

        Path workspace = null;

        try {

            Files.createDirectories(Path.of(WORKSPACE_ROOT));

            String workspaceId = UUID.randomUUID().toString();

            workspace = Path.of(WORKSPACE_ROOT, workspaceId);

            Files.createDirectories(workspace);

            // 1️⃣ Clone repository
            cloneRepo(deployment, workspace);

            // 2️⃣ Analyze repo
            RepoAnalysisResult analysis =
                    repoAnalyzerService.analyzeWorkspace(workspace);

            List<ServiceConfig> services = analysis.getServices();

            if (services.isEmpty()) {
                throw new RuntimeException("No deployable services detected");
            }

            for (ServiceConfig service : services) {

                Path servicePath = workspace.resolve(service.getPath());
                service.setPath(servicePath.toString());

                // 3️⃣ Generate Dockerfile if missing
                if (!service.isDockerfileExists()) {
                    dockerfileGenerator.generate(service);
                }

                // 4️⃣ Build Docker image
                dockerBuilder.build(service, deployment.getId());

                // image name generated by DockerBuilder
                String imageName =
                        "autopilot-" + deployment.getId();

                // 5️⃣ Push image to AWS ECR
                String imageUri = dockerPushService.pushImage(
                        deployment.getAwsRoleArn(),
                        imageName
                );

                // save pushed image URI
                deployment.setImageUri(imageUri);
            }

            deployment.setStatus(DeploymentStatus.IMAGE_PUSHED.name());

        } catch (Exception e) {

            deployment.setStatus(DeploymentStatus.FAILED.name());
            deployment.setLogs(e.getMessage());

        } finally {

            cleanup(workspace);
        }

        deploymentRepository.save(deployment);
    }

    private void cloneRepo(Deployment deployment, Path workspace) throws Exception {

        String command =
                "git clone --depth=1 -b "
                        + deployment.getBranch()
                        + " "
                        + deployment.getRepoUrl()
                        + " "
                        + workspace;

        Process process =
                Runtime.getRuntime().exec(new String[]{"bash","-c",command});

        int exit = process.waitFor();

        if (exit != 0) {
            throw new RuntimeException("Git clone failed");
        }
    }

    private void cleanup(Path workspace) {

        try {

            if (workspace == null) {
                return;
            }

            Files.walk(workspace)
                    .sorted((a, b) -> b.compareTo(a))
                    .forEach(path -> path.toFile().delete());

        } catch (Exception ignored) {}
    }
}
