package com.autopilot.service.deployment.infrastructure;

import lombok.Builder;
import lombok.Data;
import java.util.List;

/**
 * Detailed report generated by the RuntimeInfrastructureModule before deployment begins.
 */
@Data
@Builder
public class RuntimeInfrastructureReport {
    private boolean isReady;
    
    // State machine flags
    private boolean ec2Provisioned;
    private boolean cloudInitFinished;
    private boolean systemReady;
    private boolean dockerReady;
    private boolean containerdReady;
    private boolean networkingReady;
    private boolean registryReady;
    private boolean filesystemReady;
    
    // Deep verification outputs
    private String dockerVersion;
    private boolean socketAvailable;
    private boolean bridgeNetworkVerified;
    private boolean overlay2Verified;
    private boolean helloWorldPullSuccessful;
    private boolean helloWorldRunSuccessful;
    
    private List<String> remediationActionsTaken;
    private List<String> failureDiagnostics;
}
