package com.autopilot.service.deployment.v5.runtime.proxy.adapter;

import com.autopilot.service.deployment.v5.runtime.proxy.model.ReverseProxyModel;
import org.springframework.stereotype.Component;

@Component
public class CaddyAdapter implements ReverseProxyAdapter {

    @Override public boolean supports(String proxyType) { return "CADDY".equalsIgnoreCase(proxyType); }

    @Override
    public String generateConfig(ReverseProxyModel model) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by Deployrix ReverseProxyEngineV5 (Caddy Adapter)\n");
        sb.append(":80 {\n");
        if (model.isHistoryFallbackEnabled()) {
            sb.append("    try_files {path} /index.html\n");
        }
        sb.append("    reverse_proxy 127.0.0.1:8080\n");
        sb.append("}\n");
        return sb.toString();
    }

    @Override public boolean reload(String proxyType) { return true; }
    @Override public boolean verifyConfig(String config) { return config != null && config.contains(":80 {"); }
}
