package com.autopilot.service.deployment.v5.runtime.proxy.adapter;

import com.autopilot.service.deployment.v5.runtime.proxy.model.ReverseProxyModel;
import org.springframework.stereotype.Component;

@Component
public class NginxAdapter implements ReverseProxyAdapter {

    @Override public boolean supports(String proxyType) { return proxyType == null || "NGINX".equalsIgnoreCase(proxyType); }

    @Override
    public String generateConfig(ReverseProxyModel model) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by Deployrix ReverseProxyEngineV5 (NGINX Adapter)\n");
        sb.append("server {\n");
        sb.append("    listen 80;\n");
        sb.append("    server_name _;\n\n");

        if (model.getHeaderPolicy() != null && model.getHeaderPolicy().isCorsEnabled()) {
            sb.append("    add_header Access-Control-Allow-Origin \"*\";\n");
        }
        if (model.getCompressionPolicy() != null && model.getCompressionPolicy().isGzipEnabled()) {
            sb.append("    gzip on;\n    gzip_types text/plain text/css application/json application/javascript;\n");
        }

        // SPA History Fallback
        if (model.isHistoryFallbackEnabled()) {
            sb.append("    location / {\n");
            sb.append("        try_files $uri $uri/ /index.html;\n");
            sb.append("    }\n");
        } else {
            sb.append("    location / {\n");
            sb.append("        proxy_pass http://127.0.0.1:8080;\n");
            sb.append("        proxy_set_header Host $host;\n");
            sb.append("        proxy_set_header X-Real-IP $remote_addr;\n");
            sb.append("    }\n");
        }

        // OAuth routing
        if (model.getOauthRoutingTable() != null) {
            for (String oauthPath : model.getOauthRoutingTable().getOauthPrefixes()) {
                sb.append("    location ").append(oauthPath).append(" {\n");
                sb.append("        proxy_pass http://127.0.0.1:8080;\n");
                sb.append("        proxy_intercept_errors off;\n");
                sb.append("    }\n");
            }
        }

        sb.append("}\n");
        return sb.toString();
    }

    @Override public boolean reload(String proxyType) { return true; }
    @Override public boolean verifyConfig(String config) { return config != null && config.contains("server {"); }
}
