package com.autopilot.service.deployment.v5.runtime.proxy.adapter;

import com.autopilot.service.deployment.v5.runtime.proxy.model.ReverseProxyModel;
import org.springframework.stereotype.Component;

@Component
public class TraefikAdapter implements ReverseProxyAdapter {

    @Override public boolean supports(String proxyType) { return "TRAEFIK".equalsIgnoreCase(proxyType); }

    @Override
    public String generateConfig(ReverseProxyModel model) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by Deployrix ReverseProxyEngineV5 (Traefik Adapter)\n");
        sb.append("http:\n");
        sb.append("  routers:\n");
        sb.append("    app-router:\n");
        sb.append("      rule: \"PathPrefix(`/`)\"\n");
        sb.append("      service: app-service\n");
        sb.append("  services:\n");
        sb.append("    app-service:\n");
        sb.append("      loadBalancer:\n");
        sb.append("        servers:\n");
        sb.append("          - url: \"http://127.0.0.1:8080\"\n");
        return sb.toString();
    }

    @Override public boolean reload(String proxyType) { return true; }
    @Override public boolean verifyConfig(String config) { return config != null && config.contains("http:"); }
}
